//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 10. 9:29:08
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Business
{
    public partial class Transaction {

        public Transaction()
        {
            this.TransactionItems = new List<TransactionItem>();
            OnCreated();
        }

        public int TransactionID { get; set; }

        public DateTime Date { get; set; }

        public decimal Amount { get; set; }

        public string Status { get; set; }

        public int CustomerID { get; set; }

        public virtual IList<TransactionItem> TransactionItems { get; set; }

        public virtual Customer Customer { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
