//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025. 04. 10. 9:29:08
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Business
{
    public partial class TransactionItem {

        public TransactionItem()
        {
            OnCreated();
        }

        public int TransactionItemID { get; set; }

        public int TransactionID { get; set; }

        public int ProductID { get; set; }

        public int Quantity { get; set; }

        public virtual Transaction Transaction { get; set; }

        public virtual Product Product { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
